version: 2
jobs:
    build:
        docker:
            - image: circleci/buildpack-deps:18.10
        branches:
            ignore:
                - gh-pages
        working_directory: ~/project
        environment:
            - SOURCE_BRANCH: master
            - TARGET_BRANCH: gh-pages
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Create output folder with resume.html
                command: |
                    docker create -v ~ --name project alpine:3.4 /bin/true
                    docker cp . project:/project
                    docker build -t resume-make -f .docker/resume.dockerfile .
                    docker run -it --volumes-from project --name resume resume-make make
                    docker cp resume:/home/app/resume/output ~/output
            - deploy:
                name: Deploy
                command: |
                    if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
                      git config --global user.email $GH_EMAIL
                      git config --global user.name $GH_NAME

                      git clone $CIRCLE_REPOSITORY_URL out

                      cd out
                      git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
                      git rm -rf .
                      cd ..

                      cp -a ~/output/resume.html out/index.html

                      mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
                      cd out

                      git add -A
                      git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

                      git push origin $TARGET_BRANCH
                    fi
